sudo: required
services:
  # the dependencies
  - docker
# Build docker images for test running
before_install:
  - docker build -t maksymkmets/react-test -f ./finplat-ui/Dockerfile.dev ./finplat-ui
  - docker build -t maksymkmets/finplat-api-test -f ./finplat-api/Dockerfile.test ./finplat-api

# Get docker images and run testsx`
script:
  - docker run maksymkmets/react-test npm test -- --coverage
  - docker run maksymkmets/finplat-api-test gradle test

# Build docker prod images for each project
after_success:
  - docker build -t maksymkmets/finplat-ui ./finplat-ui
  - docker build -t maksymkmets/finplat-api ./finplat-api
  - docker build -t maksymkmets/nginx ./nginx

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take all created docker images and push to the docker hub
  - docker push maksymkmets/finplat-ui
  - docker push maksymkmets/finplat-api
  - docker push maksymkmets/nginx
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: Finplat
  env: Finplat-env
  bucket_name: elasticbeanstalk-eu-central-1-028811903841
  bucket_path: finplat
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY