version: '3.7'
services:
  postgresql:
    container_name: postgresql
    image: 'postgres:alpine'
    restart: 'always'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root_password'
      POSTGRES_DB: 'finplat'
    ports:
      - '5432:5432'
  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: nginx
    ports:
        - '3050:80'
    depends_on:
      - finplat-ui
  finplat-api:
    container_name: finplat-api
    build:
      dockerfile: Dockerfile.dev
      context: ./finplat-api
    depends_on:
      - postgresql
  finplat-ui:
    container_name: finplat-ui
    build:
      dockerfile: Dockerfile.dev
      context: ./finplat-ui
    depends_on:
      - finplat-api
    volumes:
      - /app/node_modules
      - ./finplat-ui:/app