version: '3.7'
services:
  postgresql:
    container_name: postgresql
    image: 'postgres:alpine'
    restart: 'always'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1111'
      POSTGRES_DB: 'finplat'
    ports:
      - '5432:5432'
  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile.dev
      context: nginx
    ports:
        - '3050:80'
    depends_on:
      - finplat-ui
  finplat-api:
    container_name: finplat-api
    build:
      dockerfile: Dockerfile.dev
      context: ./finplat-api
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/finplat
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SERVER_PORT=7070
  finplat-ui:
    container_name: finplat-ui
    build:
      dockerfile: Dockerfile.dev
      context: ./finplat-ui
    depends_on:
      - finplat-api
    volumes:
      - /app/node_modules
      - ./finplat-ui:/app